default_stages: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: shfmt
        name: format shell scripts with shfmt
        language: system
        entry: shfmt --write --indent 4
        types: [shell]
      - id: shellcheck
        name: check shellscript style
        language: system
        entry: shellcheck --severity=warning -e SC2068
        types: [shell]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.4
    hooks:
    - id: ruff
      args: ['--ignore=E741,E501']
    - id: ruff-format
